name: Test and install

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Run unit tests on Java ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          cd Recipe-Planner/recipe-planner-backend
          mvn clean test
  release:
    runs-on: ubuntu-latest
    needs: test
    name: Build and package
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build and package project
        run: mvn -f pom.xml clean package
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the target directory
        run: ls -la target